kind: pipeline
type: docker
name: proxy

steps:
  - name: build
    image: golang:1.13-alpine
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - pwd
      - go build && ls -ltrh
  - name: publish
    image: docker:19
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - pwd
      - echo "DOCKER_USERNAME=${DOCKER_USERNAME}"
      - echo "DOCKER_PASSWORD=${DOCKER_PASSWORD}"
      - docker login -u zingsono -p Zx142857
      - docker build -t mszs/porxy:latest ./
      - docker push mszs/proxy:latest

trigger:
  branch:
    - master
