kind: pipeline
type: docker
name: proxy

steps:
  - name: build
    image: golang:1.13-alpine
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - pwd
      - go build && ls -ltrh
  - name: publish
    image: docker:19
    volumes:
      - name: sock
        path: /var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - pwd
      - docker login --username=zingsono@aliyun.com --password Zx142857 registry.cn-hangzhou.aliyuncs.com
      - docker build -t registry.cn-hangzhou.aliyuncs.com/mszs/porxy:latest ./
      - docker push registry.cn-hangzhou.aliyuncs.com/mszs/porxy:latest

volumes:
  - name: sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
