---
kind: pipeline
type: docker
name: default

steps:
  # Build Project
  - name: build
    image: golang:1.13-alpine
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - pwd && go build -o ms && ls -ltrh
  # http://plugins.drone.io/drone-plugins/drone-docker/
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.cn-hangzhou.aliyuncs.com/mszs/proxy
      tags: latest
      registry: registry.cn-hangzhou.aliyuncs.com
      username: zingsono@gmail.com
      password: Zx142857


trigger:
  branch:
    - master
