kind: pipeline
type: docker
name: proxy

steps:
  - name: build
    image: golang:1.13-alpine
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - pwd
      - go build && ls -ltrh
  - name: publish
    image: plugins/docker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: mszs/proxy
    tags:
      - latest
      - 1.0.1

trigger:
  branch:
    - master
